name: simple_di
description: Simple Dependency Injection framework implementation
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.24.0
